### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by sharanyavenkat** [Hacker0x01/react-datepicker#1011]
I updated from 0.46.0 to 0.53.0 but I get the following error.

```javascript
ReferenceError: navigator is not defined
        at .../node_modules/react-datepicker/dist/react-datepicker.min.js:7:13611
        at pe (.../node_modules/react-datepicker/dist/react-datepicker.min.js:6:29542)
        at Object.<anonymous> (.../node_modules/react-datepicker/dist/react-datepicker.min.js:6:29546)
        at Object.<anonymous> (.../node_modules/react-datepicker/dist/react-datepicker.min.js:7:17502)
```
Any ideas how to get around this issue? Thanks in advance.

**Comment by cindyzwang** [comment]
had the same issue but found the answer [here](https://stackoverflow.com/questions/37078882/mocha-chai-throws-navigator-not-defined-due-to-react-router-component)
