### ISSUE TITLE
webpack error: element.loader.split is not a function

### ISSUE THREAD

**Issue by ctxhou** [Hacker0x01/react-datepicker#1158]
After `npm install`, I run `npm start` script.

It show this error:

```
/react-datepicker/node_modules/webpack-core/lib/LoadersList.js:58
  if(element.loader) return element.loader.split("!");
                                           ^

TypeError: element.loader.split is not a function
    at getLoadersFromObject (/react-datepicker/node_modules/webpack-core/lib/LoadersList.js:58:43)
    at LoadersList.<anonymous> (/react-datepicker/node_modules/webpack-core/lib/LoadersList.js:78:12)
    at Array.map (native)
    at LoadersList.match (/react-datepicker/node_modules/webpack-core/lib/LoadersList.js:70:19)
    at /react-datepicker/node_modules/webpack/lib/NormalModuleFactory.js:111:68
    at /react-datepicker/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /react-datepicker/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/react-datepicker/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /react-datepicker/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /react-datepicker/node_modules/webpack/node_modules/async/lib/async.js:723:17
```

I'm not sure that is because the webpack version is v1 or other reasons. Does anyone have the same problem?

**Comment by kblodget** [comment]
I am having the same problem and results. I have installed yarn version 1.3.2 node version 8.2.1 and tried with node version9.3.0. When I run yarn start 

reactDatePicker/react-datepicker/node_modules/webpack-core/lib/LoadersList.js:58
	if(element.loader) return element.loader.split("!");
	                                         ^

TypeError: element.loader.split is not a function

Any help would be appreciated
