### ISSUE TITLE
Logging using window causes exceptions

### ISSUE THREAD

**Issue by jin-z** [Hacker0x01/react-datepicker#1569]
window is not defined in server-side rendering

2018-12-04T23:13:36.915Z ERROR IP:::ffff:127.0.0.1 CORRID:3a003390-f81a-11e8-aa63-1bcdf5cd0c5e Master [Anonymous] ReferenceError: window is not defined
    at getLocaleObject (node_modules\react-datepicker\lib\index.js:6099:3)
    at formatDate (node_modules\react-datepicker\lib\index.js:5979:19)
    at Calendar._this.renderCurrentMonth (node_modules\react-datepicker\lib\index.js:7892:9)
    at Calendar._this.renderDefaultHeader (node_modules\react-datepicker\lib\index.js:7972:15)
    at Calendar._this.renderMonths (node_modules\react-datepicker\lib\index.js:8043:109)
    at Calendar.render (node_modules\react-datepicker\lib\index.js:8149:12)

### Expected behavior
Nothing to happen when it fails to get the locale object

### Actual behavior
Exception is thrown

### Steps to reproduce
Not entirely sure what combination of parameters causes this, but regardless, the window object should be checked first before trying to get data from it.

**Comment by pariola** [comment]
also can't use it in NEXT JS.
