### ISSUE TITLE
SSR window not defined

### ISSUE THREAD

**Issue by umakantp** [Hacker0x01/react-datepicker#1677]
### Expected behavior
On server side, rendering date picker should work as expected when the default date is set, because it doesn't find window object. I think in this case, it should ignore the locale or whatever depends on window object. (or default enable the feature and provide option to turn it off)

### Actual behavior
It throws an error, on console logs as below
```
ReferenceError: window is not defined
    at getDefaultLocale (webpack:///./node_modules/react-datepicker/es/index.js?:6118:3)
    at formatDate (webpack:///./node_modules/react-datepicker/es/index.js?:6000:23)
    at safeDateFormat (webpack:///./node_modules/react-datepicker/es/index.js?:6013:18)
    at DatePicker._this.renderDateInput (webpack:///./node_modules/react-datepicker/es/index.js?:8951:154)
    at DatePicker.render (webpack:///./node_modules/react-datepicker/es/index.js?:9029:14)
    at processChild (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:2942:18)
    at resolve (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:2795:5)
    at ReactDOMServerRenderer.render (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3185:22)
    at ReactDOMServerRenderer.read (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3144:29)
    at renderToString (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3629:27)
    at Module.reactRender (webpack:///./server/src/utils/serverUtils.js?:40:81)
    at eval (webpack:///./server/src/index.js?:144:81)
    at tryCatcher (/Users/someuser/myprojects/someproject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/someuser/myprojects/someproject/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/someuser/myprojects/someproject/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/someuser/myprojects/someproject/node_modules/bluebird/js/release/promise.js:614:10)
```

### Steps to reproduce
1. Set a default date on the calendar
2. Enable SSR and then refresh the page
3. Check the console logs on server

**Comment by umakantp** [comment]
I'll close this issue because it is already logged at https://github.com/Hacker0x01/react-datepicker/issues/1633
