### ISSUE TITLE
How to style this component? Build fails

### ISSUE THREAD

**Issue by gubikmic** [Hacker0x01/react-datepicker#1678]
I can't find a straightforward way to style this component in the documentation.

It seems changing a variable in `variables.scss` and then building is easiest but I can't even build it. When I clone and install from scratch it works but within my project it fails:

```
...
> react-datepicker@2.2.0 build:umd:dev /Users/mmg/webdev/foo/node_modules/react-datepicker
> cross-env BABEL_ENV=es rollup -c rollup.umd.config.js -i src/index.jsx -o dist/react-datepicker.js

internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/Users/mmg/webdev/foo/node_modules/react-datepicker/webpack.docs.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at module.exports (/Users/mmg/webdev/foo/node_modules/react-datepicker/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/mmg/webdev/foo/node_modules/react-datepicker/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-datepicker@2.2.0 build:docs: `cross-env MODULES=false webpack --config webpack.docs.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-datepicker@2.2.0 build:docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```

What's a good maintainable way to style this while staying inside of the npm way of importing that dependency?

**Comment by wilarz89** [comment]
I needed to figure this out too, How did you do it?

**Comment by gubikmic** [comment]
“Brute force”. I ended up overwriting the final generated CSS classes which means duplication.
So I inspected certain elements and then searched for all occurrences of that color and created a new stylesheet with all the occurrences I could find. Might have had to use ‘!important’ too, don’t remember.

**Comment by wilarz89** [comment]
Oks, I did something similar I created a css that adjusted the properties I needed.
