### ISSUE TITLE
npm run build-dev giving unexpected token in index.jsx

### ISSUE THREAD

**Issue by MoAli2016** [Hacker0x01/react-datepicker#1715]
Hi,
I am getting the following error on windows 10 machine

> cross-env BABEL_ENV=es rollup -c rollup.umd.config.js -i src/index.jsx -o dist/react-datepicker.js
src/index.jsx → es/index.js...
src/index.jsx → lib/index.js...
[!] (babel plugin) SyntaxError: C:/Code/projects/ReactJS/react-datepicker/src/index.jsx: Unexpected token (73:19)
src\index.jsx (73:19)
[!] (babel plugin) SyntaxError: C:/Code/projects/ReactJS/react-datepicker/src/index.jsx: Unexpected token (73:19)
src\index.jsx (73:19)
SyntaxError: C:/Code/projects/ReactJS/react-datepicker/src/index.jsx: Unexpected token (73:19)
    at error (C:\Code\projects\ReactJS\react-datepicker\node_modules\rollup\dist\rollup.js:185:14)
    at Object.error (C:\Code\projects\ReactJS\react-datepicker\node_modules\rollup\dist\rollup.js:17543:6)
    at promise.then.previous (C:\Code\projects\ReactJS\react-datepicker\node_modules\rollup\dist\rollup.js:17552:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**This is the error log**
10 silly lifecycle react-datepicker@2.4.0~build-dev: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development run-p build:** && run-p css:**' ]
11 silly lifecycle react-datepicker@2.4.0~build-dev: Returned: code: 1  signal: null
12 info lifecycle react-datepicker@2.4.0~build-dev: Failed to exec build-dev script
13 verbose stack Error: react-datepicker@2.4.0 build-dev: `cross-env NODE_ENV=development run-p build:** && run-p css:**`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid react-datepicker@2.4.0
15 verbose cwd C:\Code\projects\ReactJS\react-datepicker
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-dev"
18 verbose node v8.11.3
19 verbose npm  v6.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error react-datepicker@2.4.0 build-dev: `cross-env NODE_ENV=development run-p build:** && run-p css:**`
22 error Exit status 1
23 error Failed at the react-datepicker@2.4.0 build-dev script.

Any help, I am not sure how to get it built.

**Comment by MoAli2016** [comment]
I resolved the error above by adding to my .babelrc
{
	"plugins": [["transform-class-properties", { "spec": true }]]
}
and got passed the error to another one
unexpected token (627,6) in index.jsx which this line `<WrappedCalendar`, please can anyone help. What I do not understand is that I cloned the project and did `npm install` then `npm run build` there must something wrong I am doing.

**Comment by MoAli2016** [comment]
Ok this is now resolved, I was missing config.plugins line in my .babelrc I have no idea why it happened, I cloned the repo fine.
