### ISSUE TITLE
Server-side rendering broken in 0.22

### ISSUE THREAD

**Issue by strawbrary** [Hacker0x01/react-datepicker#352]
It looks like 0.22 cannot be used server-side due to reliance on `document`. Here is a simple example that worked in 0.21.
```javascript
var React = require('react');
var ReactDOM = require('react-dom/server');
var DatePicker = require('react-datepicker');

ReactDOM.renderToString(React.createElement(DatePicker));
```

Result:
```
ReferenceError: document is not defined
    at /Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:6:16300
    at Object.o (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:6:16334)
    at e (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:668)
    at Object.t.__esModule.default (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:6:12242)
    at e (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:668)
    at Object.e.exports (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:906)
    at e (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:668)
    at t.__esModule.default (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:755)
    at /Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:760
    at n.(anonymous function).exports (/Users/strawbrary/projects/datepicker/node_modules/react-datepicker/dist/react-datepicker.min.js:1:143)
```

**Comment by rafeememon** [comment]
Looks like this was introduced when we upgraded `react-tether` to v0.3.1, which has an eagerly-evaluated `document.body` reference.

**Comment by rafeememon** [comment]
@strawbrary, can you verify that changing the portion of referenced in the stacktrace fixes your problem?

Around react-datepicker.min.js:6:16300:
```
...renderElementTo:document.body...
```

Change to:
```
...renderElementTo:document&&document.body...
```

**Comment by rafeememon** [comment]
@strawbrary, can you verify that changing the portion of code referenced in the stacktrace fixes your problem?

Around react-datepicker.min.js:6:16300:
```
...renderElementTo:document.body...
```

Change to:
```
...renderElementTo: typeof document !== 'undefined' && document.body...
```

**Comment by strawbrary** [comment]
@rafeememon Adding `typeof document !== 'undefined'` works, thanks.

**Comment by rafeememon** [comment]
Thanks -- going to make a PR into `react-tether`

**Comment by rafeememon** [comment]
Should be fixed in v0.23.1

**Comment by juancarlosfarah** [comment]
I'm using v0.23.1 and I'm getting the error.

**Comment by rafeememon** [comment]
@martijnrusschen, it looks like v0.23.1 didn't publish correctly, can you try deleting node_modules, re-installing and republishing v0.23.2?

**Comment by martijnrusschen** [comment]
Can you try this again with v0.23.2?

**Comment by juancarlosfarah** [comment]
@martijnrusschen, it's working for me with 0.23.2. Awesome.

**Comment by rafeememon** [comment]
Woot!
