### ISSUE TITLE
Cannot read properties of undefined (reading 'openToDate') in production only

### ISSUE THREAD

**Issue by GuffyG** [Hacker0x01/react-datepicker#4186]
There is no issue in development but when a build is created then this issue happening.

TypeError: Cannot read properties of undefined (reading 'openToDate')
    at n.getPreSelection (react-datepicker.min.js:2746:1)
    at n.calcInitialState (react-datepicker.min.js:2749:1)
    at new n (react-datepicker.min.js:3207:10)
    at Bi (react-dom.production.min.js:2949:1)
    at Oc (react-dom.production.min.js:4077:1)
    at pu (react-dom.production.min.js:6468:1)
    at as (react-dom.production.min.js:6127:1)
    at os (react-dom.production.min.js:6121:21)
    at rs (react-dom.production.min.js:6107:1)
    at Yu (react-dom.production.min.js:5830:1)
nc @ react-dom.production.min.js:3912
n.callback @ react-dom.production.min.js:3929
Ei @ react-dom.production.min.js:2892
uu @ react-dom.production.min.js:5524
t @ react-dom.production.min.js:5489
cu @ react-dom.production.min.js:5468
(anonymous) @ react-dom.production.min.js:6207
us @ react-dom.production.min.js:6168
Ku @ react-dom.production.min.js:5891
jo @ react-dom.production.min.js:2475
(anonymous) @ react-dom.production.min.js:5717
![Uploading Screenshot 2023-08-02 at 2.55.30 PM.png…]()

**Comment by gyananshu07** [comment]
Hey, can you specify where this issue is happening, I am working on this, it will help me.

**Comment by bngmnn** [comment]
Experienced the same issue

For a quick fix I downgraded to my latest installed version of react-datepicker which was 4.11. Didn't have the time to investigate which version/commit might have introduced that error.

@gyananshu07 In my case it was giving me the error
TypeError: Cannot read properties of undefined (reading 'overflow')
which occured when I clicked into my Datepicker component.

Might be because of the selected prop on it

**Comment by GuffyG** [comment]
> Hey, can you specify where this issue is happening, I am working on this, it will help me.

Hi, I updated my app environment to latest and also updated all dependencies and found it working now.

**Comment by KumailP** [comment]
> For a quick fix I downgraded to my latest installed version of react-datepicker which was 4.11.

Same issue as OP and this fixed it

**Comment by chetannada** [comment]
Hi @GuffyG 
The image you added in description `[Uploading Screenshot 2023-08-02 at 2.55.30 PM.png…](https://github.com/Hacker0x01/react-datepicker/issues/4186)` is unable to open, it's redirected to the same issue. Please upload proper image.

**Comment by bobysharma** [comment]
i am facing same issue    Uncaught TypeError: Cannot read properties of undefined (reading 'openToDate')
    at a.getPreSelection (react-datepicker.min.js:3007:1)
    at a.calcInitialState (react-datepicker.min.js:3010:1)
    at new a (react-datepicker.min.js:3488:8)
    at cn (react-dom.production.min.js:3351:1)
    at Ao (react-dom.production.min.js:4622:1)
    at Ds (react-dom.production.min.js:7033:1)
    at gi (react-dom.production.min.js:6519:1)
    at hi (react-dom.production.min.js:6508:1)
    at fi (react-dom.production.min.js:6490:1)
![errror](https://github.com/Hacker0x01/react-datepicker/assets/69707812/e036b1dc-0f49-4922-9a4a-1e423604f896)

    at ri (react-dom.production.min.js:6212:4)

**Comment by jmiremba** [comment]
Seeing the same exact issue after upgrading my envronment. Tried to revert this component to 4.1.1, which is what I had before, but all production builds still exhibit the issue. What steps should happen to revert to a version that works?

**Comment by yschristian** [comment]
<img width="960" alt="Screenshot 2024-02-08 185607" src="https://github.com/Hacker0x01/react-datepicker/assets/89045591/14053f32-27f2-47fc-9845-fd2b826db353">
 
 i have the same issue

**Comment by lucasbatiiista** [comment]
Hello @yschristian @GuffyG 

How are you calling the component? Could you post a screenshot?

**Comment by gmganesh3110** [comment]
Anybody found solution for this issue?

**Comment by gmganesh3110** [comment]
Update react-date-timepicker to above versions one by one it will work
