### ISSUE TITLE
Getting error on input click

### ISSUE THREAD

**Issue by Robinfr** [Hacker0x01/react-datepicker#765]
I'm getting an error as soon I click on the input:

```js
Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (38 has parents 31 and 37).
Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (38 has parents 31 and 37).
    at invariant (http://localhost:8080/bundle.js:9098:16)
    at Object.onSetChildren (http://localhost:8080/bundle.js:11602:79)
    at callHook (http://localhost:8080/bundle.js:16422:9)
    at emitEvent (http://localhost:8080/bundle.js:16434:8)
    at Object.onSetChildren (http://localhost:8080/bundle.js:16706:6)
    at ReactDOMComponent.setChildrenForInstrumentation (http://localhost:8080/bundle.js:22558:39)
    at ReactDOMComponent._updateChildren (http://localhost:8080/bundle.js:22761:40)
    at ReactDOMComponent.updateChildren (http://localhost:8080/bundle.js:22700:13)
    at ReactDOMComponent._updateDOMChildren (http://localhost:8080/bundle.js:19940:13)
    at ReactDOMComponent.updateComponent (http://localhost:8080/bundle.js:19758:11)
```

All I'm doing is rendering the DatePicker..

```js
(
        <DatePicker
            selected={moment()}
            onChange={this._onChange}
        />
 );
```

I'm using React 15.4.2 and the latest version of react-datepicker.

Edit: React 15.4.2

**Comment by benbcai** [comment]
I am also seeing this warning in Devtools. I don't know if there is a problem in react-datepicker or in react itself. I'm using react 15.4.2. Anyone else having this issue and know what the cause is?

**Comment by alex-shamshurin** [comment]
Could you provide more steps to reproduce?

**Comment by Robinfr** [comment]
Uhm, not really, it literally happens simply by using React 15.4.2 and the latest react-datepicker.. I tried to create a fiddle but I cannot get it working properly.

Maybe someone else can get it working without the React errors? https://jsfiddle.net/7g5e58s2/1/
